# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
#


include:
  - board: nice_nano_v2
    shield: nice_view_corne_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

  - board: nice_nano_v2
    shield: nice_view_corne_right
    snippet: studio-rpc-usb-uart

  - board: nice_nano_v2
    shield: settings_reset
    snippet: studio-rpc-usb-uart

  - board: nice_nano_v2
    shield: settings_reset
    snippet: studio-rpc-usb-uart


#  - board: piantor_pro_bt_left
#    snippet: studio-rpc-usb-uart
#    shield: nice_view
#    cmake-args: -DCONFIG_ZMK_STUDIO=y
#  - board: piantor_pro_bt_right
#    shield: nice_view
#    snippet: studio-rpc-usb-uart

#  - board: piantor_pro_bt_left
#    shield: settings_reset
#    snippet: studio-rpc-usb-uart
#  - board: piantor_pro_bt_right
#    shield: settings_reset
#    snippet: studio-rpc-usb-uart
